### ISSUE TITLE
Enable Link-Time Optimization (LTO)

### ISSUE THREAD

**Issue by zamazan4ik** [agentic-labs/lsproxy#61]
Hi!

I noticed that in the `Cargo.toml` [file](https://github.com/agentic-labs/lsproxy/blob/main/lsproxy/Cargo.toml) Link-Time Optimization (LTO) for the project is not enabled. I suggest switching it on since it will reduce the binary size (always a good thing to have) and will likely improve the application's performance a bit.

I suggest enabling LTO only for the Release builds so as not to sacrifice the developers' experience while working on the project since LTO consumes an additional amount of time to finish the compilation routine. If you think that a regular Release build should not be affected by such a change as well, then I suggest adding an additional `dist` or `release-lto` profile where in addition to regular `release` optimizations LTO will also be added. Such a change simplifies life for maintainers and others interested in the project persons who want to build the most performant version of the application. Using ThinLTO should also help to reduce the build-time overhead with LTO. If we enable it on the Cargo profile level, users, who install the application with `cargo install` or building the Release Docker image, will get the LTO-optimized version "automatically". E.g., check `cargo-outdated` Release [profile](https://github.com/kbknapp/cargo-outdated/blob/master/Cargo.toml#L48).

Basically, it can be enabled with the following lines:

```
[profile.release]
lto = true
```

I have made quick tests (Fedora 41, Rustc 1.82) by adding `lto = true` to the Release profile. The binary size reduction is from 24 Mib to 21 Mib.

Thank you.

**Comment by robmck1995** [comment]
Hey thanks so much for the contribution! I'm not familiar with LTO but based on some quick research it seems like it can produce smaller binaries and slightly faster code but at the expense of longer compile times.

My take is that it might make sense to add this in the future, but given right now we're pushing out releases pretty quickly, compile times do matter a lot (especially when we're building a docker image for a non-native platform using emulation). And I think the size of the whole docker image is more the dominant factor than the binary itself.

Curious to hear your take!

**Comment by zamazan4ik** [comment]
If you care about the Release profile compile time, I suggest you create a dedicated profile with LTO (smth like `[profile.heavy-release]` where you can enable all heavy compiler optimizations. Then, you are free to use this profile in creating heavily optimized builds (and users who build Docker images manually will also be able to choose this option). As an example of multiple Cargo profiles, I have a good one: https://github.com/girlbossceo/conduwuit/blob/main/Cargo.toml#L547

**Comment by maks-ivanov** [comment]
@zamazan4ik hey, is there a usecase where the binary size reduction is meaningful?
the overall performance is dominated by language servers like jdtls or jedi, which are much slower and resource-intensive than our rust code.
this hasn't been a priority so far, the reduction is modest and doesn't seem worth adding another profile but happy to reevaluate in the future

**Comment by zamazan4ik** [comment]
> hey, is there a usecase where the binary size reduction is meaningful?

Binary size is only one thing that is easy to measure (that's why I shown it). Another point is allowing the compiler to perform more aggressive optimizations that lead to better performance/UX/TCO/etc. Even if the majority of the performance/binary size is coming from 3rd party, FMPOV it's not the reason to avoid additional optimizations applied to the Rust part. However, the final decision on this question of course is up to you :)

> happy to reevaluate in the future

In this case, I suggested just leaving the issue open with such a mark instead of "Not planned".
