### ISSUE TITLE
starting docker fail

### ISSUE THREAD

**Issue by XuhaoZhao** [agentic-labs/lsproxy#75]
PS C:\Users\Administrator> docker run -p 4444:4444 -v /c/Users/Administrator/Desktop/spring-cloud-consul:/mnt/workspace agenticlabs/lsproxy
Starting...
[2024-11-20T09:13:13Z INFO  lsproxy] Logger initialized
Error: Custom { kind: Other, error: "Failed to spawn Java process: No such file or directory (os error 2)" }

**Comment by robmck1995** [comment]
Thanks for pointing this out. We had incorrectly not added the java dependencies to the release docker file. You should be good to go now by re-pulling `agenticlabs/lsproxy:latest` or `agenticlabs/lsproxy:0.1.6`!

**Comment by XuhaoZhao** [comment]
thanks
